# Generated by Django 3.2.1 on 2021-08-25 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interfaces',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('creator', models.TextField(help_text='创建人', null=True, verbose_name='创建人')),
                ('updater', models.TextField(help_text='更新人', null=True, verbose_name='更新人')),
                ('is_delete', models.IntegerField(default=0, help_text='是否删除', null=True, verbose_name='是否删除')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='接口名称', max_length=200, verbose_name='接口名称')),
                ('request', models.TextField(help_text='请求信息', verbose_name='请求数据')),
                ('path', models.CharField(help_text='接口路径', max_length=200, unique=True, verbose_name='接口路径')),
                ('method', models.CharField(help_text='请求方式', max_length=200, verbose_name='请求方式')),
                ('rig_id', models.IntegerField(blank=True, help_text='网关api_id', null=True, verbose_name='网关api_id')),
                ('rig_env', models.IntegerField(blank=True, help_text='网关环境', null=True, verbose_name='网关环境')),
                ('threads', models.IntegerField(help_text='线程数', verbose_name='线程数')),
                ('rate', models.IntegerField(help_text='加压速率', verbose_name='加压速率')),
                ('execution_time', models.IntegerField(help_text='执行时间', verbose_name='执行时间')),
                ('latency_time', models.IntegerField(help_text='等待时间', verbose_name='等待时间')),
                ('assertstr', models.CharField(blank=True, help_text='断言', max_length=50, null=True, verbose_name='断言')),
                ('system_id', models.ForeignKey(help_text='系统id', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='system.system')),
            ],
            options={
                'verbose_name': '接口信息',
                'verbose_name_plural': '接口信息',
                'db_table': 'p_interfaces',
            },
        ),
    ]
