# Generated by Django 3.2.1 on 2021-08-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfaces',
            old_name='body',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='interfaces',
            old_name='system',
            new_name='system_id',
        ),
        migrations.AddField(
            model_name='interfaces',
            name='creator',
            field=models.TextField(help_text='创建人', null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='interfaces',
            name='is_delete',
            field=models.IntegerField(help_text='是否删除', null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='interfaces',
            name='updater',
            field=models.TextField(help_text='更新人', null=True, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='assertstr',
            field=models.CharField(blank=True, help_text='断言', max_length=50, null=True, verbose_name='断言'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='rig_env',
            field=models.IntegerField(blank=True, help_text='网关环境', null=True, verbose_name='网关环境'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='rig_id',
            field=models.IntegerField(blank=True, help_text='网关api_id', null=True, verbose_name='网关api_id'),
        ),
    ]
