# Generated by Django 3.1.3 on 2021-07-07 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='项目名称', max_length=50, verbose_name='项目名称')),
                ('include', models.TextField(help_text='包含的接口', verbose_name='包含的接口')),
                ('creator', models.CharField(help_text='创建人', max_length=50, verbose_name='创建人')),
                ('updater', models.CharField(help_text='更新人', max_length=50, verbose_name='更新人')),
                ('desc', models.CharField(blank=True, default='', help_text='简要描述', max_length=200, null=True, verbose_name='简要描述')),
                ('system_id', models.ForeignKey(help_text='系统id', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='system.system')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 'p_projects',
            },
        ),
    ]
