# Generated by Django 3.2.1 on 2021-08-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_delete',
            field=models.IntegerField(help_text='是否删除', null=True, verbose_name='是否删除'),
        ),
    ]
