# Generated by Django 3.1.3 on 2021-07-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('id', models.AutoField(help_text='系统id', primary_key=True, serialize=False, verbose_name='系统id')),
                ('name', models.CharField(help_text='系统名称', max_length=50, verbose_name='系统名称')),
                ('annotation', models.TextField(help_text='备注', max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '系统信息',
                'verbose_name_plural': '系统信息',
                'db_table': 'p_system',
            },
        ),
    ]
