# Generated by Django 3.2.1 on 2021-08-25 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execute_logs', '0001_initial'),
        ('projects', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExecutiveOutcomes',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('creator', models.TextField(help_text='创建人', null=True, verbose_name='创建人')),
                ('updater', models.TextField(help_text='更新人', null=True, verbose_name='更新人')),
                ('is_delete', models.IntegerField(default=0, help_text='是否删除', null=True, verbose_name='是否删除')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('interfacename', models.CharField(help_text='接口名称', max_length=200, verbose_name='接口名称')),
                ('requests', models.IntegerField(help_text='请求数', verbose_name='请求数')),
                ('fails', models.IntegerField(help_text='失败数', verbose_name='失败数')),
                ('threads', models.IntegerField(help_text='线程数', verbose_name='线程数')),
                ('average', models.CharField(help_text='平均数', max_length=200, verbose_name='平均数')),
                ('median', models.CharField(help_text='中位数', max_length=200, verbose_name='中位数')),
                ('ninety_percentile', models.CharField(help_text='90%百分位', max_length=200, verbose_name='90%百分位')),
                ('ninety_five_percentile', models.CharField(help_text='95%百分位', max_length=200, verbose_name='95%百分位')),
                ('ninety_nine_percentile', models.CharField(help_text='99%百分位', max_length=200, verbose_name='99%百分位')),
                ('least_value', models.CharField(help_text='最小值', max_length=200, verbose_name='最小值')),
                ('maximum_value', models.CharField(help_text='最大值', max_length=200, verbose_name='最大值')),
                ('error_rate', models.CharField(help_text='平均数', max_length=200, verbose_name='平均数')),
                ('tps', models.CharField(help_text='吞吐量', max_length=200, verbose_name='吞吐量')),
                ('receives_traffic', models.CharField(help_text='接受流量', max_length=200, verbose_name='接受流量')),
                ('send_traffic', models.CharField(help_text='发送流量', max_length=200, verbose_name='发送流量')),
                ('execute_log', models.ForeignKey(help_text='执行记录id', on_delete=django.db.models.deletion.CASCADE, related_name='interface_executive_outcomes', to='execute_logs.executelogs')),
                ('project', models.ForeignKey(help_text='项目id', on_delete=django.db.models.deletion.CASCADE, related_name='interface_executive_outcomes', to='projects.projects')),
                ('system', models.ForeignKey(help_text='系统id', on_delete=django.db.models.deletion.CASCADE, related_name='interface_executive_outcomes', to='system.system')),
            ],
            options={
                'verbose_name': '接口执行结果',
                'verbose_name_plural': '接口执行结果',
                'db_table': 'p_interface_executive_outcomes',
            },
        ),
    ]
