# Generated by Django 3.2.1 on 2021-08-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces_executive_outcomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexecutiveoutcomes',
            name='creator',
            field=models.TextField(help_text='创建人', null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='projectexecutiveoutcomes',
            name='is_delete',
            field=models.IntegerField(help_text='是否删除', null=True, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='projectexecutiveoutcomes',
            name='updater',
            field=models.TextField(help_text='更新人', null=True, verbose_name='更新人'),
        ),
    ]
