# Generated by Django 3.2.1 on 2021-12-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecuteLogs',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('creator', models.TextField(help_text='创建人', null=True, verbose_name='创建人')),
                ('updater', models.TextField(help_text='更新人', null=True, verbose_name='更新人')),
                ('is_delete', models.IntegerField(default=0, help_text='是否删除', null=True, verbose_name='是否删除')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('interface_id', models.IntegerField(help_text='接口用例ID', verbose_name='接口用例ID')),
                ('reportdata', models.TextField(help_text='报告数据', verbose_name='报告数据')),
            ],
            options={
                'verbose_name': '执行记录',
                'verbose_name_plural': '执行记录',
                'db_table': 'p_execute_logs',
            },
        ),
    ]
