# Generated by Django 3.2.1 on 2021-12-23 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interfaces_executive_outcomes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('creator', models.TextField(help_text='创建人', null=True, verbose_name='创建人')),
                ('updater', models.TextField(help_text='更新人', null=True, verbose_name='更新人')),
                ('is_delete', models.IntegerField(default=0, help_text='是否删除', null=True, verbose_name='是否删除')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='报告名称', max_length=200, unique=True, verbose_name='报告名称')),
                ('path', models.URLField(help_text='报告文件地址', verbose_name='报告文件地址')),
                ('interface_execute', models.ForeignKey(help_text='所属接口执行结果id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='interfaces_executive_outcomes.projectexecutiveoutcomes')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'db_table': 'p_reports',
            },
        ),
    ]
