# Generated by Django 3.1.3 on 2021-07-07 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configures',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('threads', models.IntegerField(help_text='线程数', verbose_name='线程数')),
                ('rate', models.IntegerField(help_text='加压速率', verbose_name='加压速率')),
                ('latency_time', models.IntegerField(help_text='等待时间', verbose_name='等待时间')),
                ('execution_time', models.IntegerField(help_text='执行时间', verbose_name='执行时间')),
                ('project', models.ForeignKey(help_text='所属接口', on_delete=django.db.models.deletion.CASCADE, related_name='configures', to='projects.projects')),
            ],
            options={
                'verbose_name': '配置信息',
                'verbose_name_plural': '配置信息',
                'db_table': 'p_configures',
            },
        ),
    ]
